export const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
export const SEARCH_BY_NAME = 'SEARCH_BY_NAME';
export const FILTER_BY_NAME = 'FILTER_BY_NAME';
export const FILTER_BY_GENRES = 'FILTER_BY_GENRES';
export const SORT_BY_ALPHABET = 'SORT_BY_ALPHABET';
export const SORT_BY_RATING = 'SORT_BY_RATING';
export const GET_VIDEOGAME_DETAIL = 'GET_VIDEOGAME_DETAIL';